### PR TITLE
Upload to update folder

### PR DESCRIPTION
**Pull request by ItsVaidas**
If "update" folder exists, upload the updates to that folder, so that it would automaticly update itself on restart without overwriting the plugin in plugins folder avoiding issues with that.

### CODE REVIEW

**Comment by NewAmazingPVP** [comment]
@ItsVaidas So the point of this is to have a separate way to get/download latest updates without overwriting the plugin in the plugins folder, right?

**Comment by ItsVaidas** [comment]
> @ItsVaidas So the point of this is to have a separate way to get/download latest updates without overwriting the plugin in the plugins folder, right?

Paper (and all of its forks) automaticly updates (moves) plugins that are in the folder "plugins/update". Overwriting the plugin while the server is working can lead to a lot of errors. In my case viaversions didn't allow any player to join because of those errors, I had to manually fix this issue.

**Comment by NewAmazingPVP** [comment]
@ItsVaidas ah I see now. I wasn't aware of this feature in papermc. I'll merge this and release new version soon

**Comment by NewAmazingPVP** [comment]
Thanks for committing/contributing!

**Pull request merged**
